2022-12-28 15:26:53,724 num rows for train: 5233
2022-12-28 15:26:54,089 best_score 0.86106
2022-12-28 15:27:11,305 table raw_rent_messages created
2022-12-28 15:27:11,386 data loaded to raw_rent_messages
2022-12-28 15:27:11,388 current rows in table: 6542
2022-12-28 15:27:53,963 table raw_rent_messages created
2022-12-28 15:27:53,965 current rows in table: 6542
2022-12-28 15:28:42,865 table raw_rent_messages created
2022-12-28 15:28:42,868 current rows in table: 6542
2022-12-28 15:28:43,208 App initialized
2022-12-28 15:28:43,212 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 15:28:43,213 [33mPress CTRL+C to quit[0m
2022-12-28 15:28:57,807 172.18.0.1 - - [28/Dec/2022 15:28:57] "[33mGET / HTTP/1.1[0m" 404 -
2022-12-28 15:28:57,892 172.18.0.1 - - [28/Dec/2022 15:28:57] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2022-12-28 15:29:05,500 172.18.0.1 - - [28/Dec/2022 15:29:05] "[33mGET / HTTP/1.1[0m" 404 -
2022-12-28 15:29:05,580 172.18.0.1 - - [28/Dec/2022 15:29:05] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2022-12-28 15:29:18,363 172.18.0.1 - - [28/Dec/2022 15:29:18] "GET /messages HTTP/1.1" 200 -
2022-12-28 15:29:26,542 Exception on /messages/1 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/srv/src/service.py", line 39, in pridict_labell
    vectorized=vectorizer.transform(msg['txt'])
NameError: name 'vectorizer' is not defined
2022-12-28 15:29:26,543 172.18.0.1 - - [28/Dec/2022 15:29:26] "[35m[1mGET /messages/1 HTTP/1.1[0m" 500 -
2022-12-28 15:32:55,039 table raw_rent_messages created
2022-12-28 15:32:55,042 current rows in table: 6542
2022-12-28 15:32:55,382 App initialized
2022-12-28 15:32:55,387 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 15:32:55,387 [33mPress CTRL+C to quit[0m
2022-12-28 15:32:59,895 Exception on /messages/1 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/srv/src/service.py", line 40, in pridict_labell
    predicted_label = model.predict(msg['txt'])
  File "/usr/local/lib/python3.8/site-packages/sklearn/linear_model/_base.py", line 447, in predict
    scores = self.decision_function(X)
  File "/usr/local/lib/python3.8/site-packages/sklearn/linear_model/_base.py", line 429, in decision_function
    X = self._validate_data(X, accept_sparse="csr", reset=False)
  File "/usr/local/lib/python3.8/site-packages/sklearn/base.py", line 577, in _validate_data
    X = check_array(X, input_name="X", **check_params)
  File "/usr/local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 871, in check_array
    raise ValueError(
ValueError: Expected 2D array, got scalar array instead:
array=#—Å–Ω–∏–º—É  –∫–æ–º–Ω–∞—Ç—É –≤ –ª–∏–º–∞—Å—Å–æ–ª–µ –∏–ª–∏ –Ω–µ–¥–∞–ª–µ–∫–æ –æ—Ç –Ω–µ–≥–æ. —Å –Ω–∞—á–∞–ª–∞ –∞–≤–≥—É—Å—Ç–∞. –ª—é–±—ã–µ –ø—Ä–µ–¥–ª–æ–∂–µ–Ω–∏—è –≤ –ª—Å.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
2022-12-28 15:32:59,897 172.18.0.1 - - [28/Dec/2022 15:32:59] "[35m[1mGET /messages/1 HTTP/1.1[0m" 500 -
2022-12-28 15:40:20,840 num rows for train: 5233
2022-12-28 15:40:21,206 best_score 0.86106
2022-12-28 15:40:27,727 table raw_rent_messages created
2022-12-28 15:40:27,729 current rows in table: 6542
2022-12-28 15:40:28,073 App initialized
2022-12-28 15:40:28,078 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 15:40:28,078 [33mPress CTRL+C to quit[0m
2022-12-28 15:40:35,767 Exception on /messages/1 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/srv/src/service.py", line 40, in pridict_labell
    predicted_label = model.predict(msg['txt'])
  File "/usr/local/lib/python3.8/site-packages/sklearn/linear_model/_base.py", line 447, in predict
    scores = self.decision_function(X)
  File "/usr/local/lib/python3.8/site-packages/sklearn/linear_model/_base.py", line 429, in decision_function
    X = self._validate_data(X, accept_sparse="csr", reset=False)
  File "/usr/local/lib/python3.8/site-packages/sklearn/base.py", line 577, in _validate_data
    X = check_array(X, input_name="X", **check_params)
  File "/usr/local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 871, in check_array
    raise ValueError(
ValueError: Expected 2D array, got scalar array instead:
array=#—Å–Ω–∏–º—É  –∫–æ–º–Ω–∞—Ç—É –≤ –ª–∏–º–∞—Å—Å–æ–ª–µ –∏–ª–∏ –Ω–µ–¥–∞–ª–µ–∫–æ –æ—Ç –Ω–µ–≥–æ. —Å –Ω–∞—á–∞–ª–∞ –∞–≤–≥—É—Å—Ç–∞. –ª—é–±—ã–µ –ø—Ä–µ–¥–ª–æ–∂–µ–Ω–∏—è –≤ –ª—Å.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
2022-12-28 15:40:35,768 172.18.0.1 - - [28/Dec/2022 15:40:35] "[35m[1mGET /messages/1 HTTP/1.1[0m" 500 -
2022-12-28 15:41:25,979 table raw_rent_messages created
2022-12-28 15:41:25,981 current rows in table: 6542
2022-12-28 15:41:26,323 App initialized
2022-12-28 15:41:26,327 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 15:41:26,327 [33mPress CTRL+C to quit[0m
2022-12-28 15:41:29,455 Exception on /messages/1 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/srv/src/service.py", line 39, in pridict_labell
    vectorized=vectorizer.transform(msg['txt'])
  File "/usr/local/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 2103, in transform
    X = super().transform(raw_documents)
  File "/usr/local/lib/python3.8/site-packages/sklearn/feature_extraction/text.py", line 1381, in transform
    raise ValueError(
ValueError: Iterable over raw text documents expected, string object received.
2022-12-28 15:41:29,456 172.18.0.1 - - [28/Dec/2022 15:41:29] "[35m[1mGET /messages/1 HTTP/1.1[0m" 500 -
2022-12-28 15:42:50,680 table raw_rent_messages created
2022-12-28 15:42:50,683 current rows in table: 6542
2022-12-28 15:42:51,027 App initialized
2022-12-28 15:42:51,031 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 15:42:51,031 [33mPress CTRL+C to quit[0m
2022-12-28 15:42:52,355 172.18.0.1 - - [28/Dec/2022 15:42:52] "GET /messages/1 HTTP/1.1" 200 -
2022-12-28 15:43:03,151 172.18.0.1 - - [28/Dec/2022 15:43:03] "GET /messages/2 HTTP/1.1" 200 -
2022-12-28 15:43:07,416 172.18.0.1 - - [28/Dec/2022 15:43:07] "GET /messages/3 HTTP/1.1" 200 -
2022-12-28 15:43:21,665 172.18.0.1 - - [28/Dec/2022 15:43:21] "GET /messages/1028 HTTP/1.1" 200 -
2022-12-28 15:43:25,001 172.18.0.1 - - [28/Dec/2022 15:43:25] "GET /messages/10 HTTP/1.1" 200 -
2022-12-28 15:43:32,613 172.18.0.1 - - [28/Dec/2022 15:43:32] "GET /messages/5000 HTTP/1.1" 200 -
2022-12-28 15:46:03,005 table raw_rent_messages created
2022-12-28 15:46:03,007 current rows in table: 6542
2022-12-28 15:46:03,354 App initialized
2022-12-28 15:46:03,358 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 15:46:03,358 [33mPress CTRL+C to quit[0m
2022-12-28 15:46:05,404 172.18.0.1 - - [28/Dec/2022 15:46:05] "GET /messages/5000 HTTP/1.1" 200 -
2022-12-28 15:49:00,576 table raw_rent_messages created
2022-12-28 15:49:00,578 current rows in table: 6542
2022-12-28 15:49:00,939 App initialized
2022-12-28 15:49:00,943 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 15:49:00,943 [33mPress CTRL+C to quit[0m
2022-12-28 15:49:03,084 Exception on /messages/5000 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/srv/src/service.py", line 40, in pridict_labell
    predicted_score = model.predict(vectorized)[1]
IndexError: index 1 is out of bounds for axis 0 with size 1
2022-12-28 15:49:03,085 172.18.0.1 - - [28/Dec/2022 15:49:03] "[35m[1mGET /messages/5000 HTTP/1.1[0m" 500 -
2022-12-28 15:49:21,813 table raw_rent_messages created
2022-12-28 15:49:21,815 current rows in table: 6542
2022-12-28 15:49:22,155 App initialized
2022-12-28 15:49:22,159 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 15:49:22,159 [33mPress CTRL+C to quit[0m
2022-12-28 15:49:22,698 Exception on /messages/5000 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/srv/src/service.py", line 40, in pridict_labell
    predicted_score = model.predict_proba(vectorized)[1]
IndexError: index 1 is out of bounds for axis 0 with size 1
2022-12-28 15:49:22,699 172.18.0.1 - - [28/Dec/2022 15:49:22] "[35m[1mGET /messages/5000 HTTP/1.1[0m" 500 -
2022-12-28 15:49:43,958 table raw_rent_messages created
2022-12-28 15:49:43,961 current rows in table: 6542
2022-12-28 15:49:44,303 App initialized
2022-12-28 15:49:44,308 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 15:49:44,308 [33mPress CTRL+C to quit[0m
2022-12-28 15:49:44,981 172.18.0.1 - - [28/Dec/2022 15:49:44] "GET /messages/5000 HTTP/1.1" 200 -
2022-12-28 15:50:03,863 table raw_rent_messages created
2022-12-28 15:50:03,865 current rows in table: 6542
2022-12-28 15:50:04,228 App initialized
2022-12-28 15:50:04,232 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 15:50:04,232 [33mPress CTRL+C to quit[0m
2022-12-28 15:50:05,052 172.18.0.1 - - [28/Dec/2022 15:50:05] "GET /messages/5000 HTTP/1.1" 200 -
2022-12-28 15:50:10,271 172.18.0.1 - - [28/Dec/2022 15:50:10] "GET /messages/10 HTTP/1.1" 200 -
2022-12-28 15:50:22,217 172.18.0.1 - - [28/Dec/2022 15:50:22] "GET /messages/66 HTTP/1.1" 200 -
2022-12-28 15:50:29,594 172.18.0.1 - - [28/Dec/2022 15:50:29] "GET /messages/243 HTTP/1.1" 200 -
2022-12-28 15:50:35,266 172.18.0.1 - - [28/Dec/2022 15:50:35] "GET /messages/2111 HTTP/1.1" 200 -
2022-12-28 15:50:38,306 172.18.0.1 - - [28/Dec/2022 15:50:38] "GET /messages/21 HTTP/1.1" 200 -
2022-12-28 15:50:41,750 172.18.0.1 - - [28/Dec/2022 15:50:41] "GET /messages/5001 HTTP/1.1" 200 -
2022-12-28 16:02:02,579 table raw_rent_messages created
2022-12-28 16:02:02,581 current rows in table: 6542
2022-12-28 16:02:02,939 App initialized
2022-12-28 16:02:02,943 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 16:02:02,943 [33mPress CTRL+C to quit[0m
2022-12-28 16:02:07,172 172.18.0.1 - - [28/Dec/2022 16:02:07] "GET /messages/5001 HTTP/1.1" 200 -
2022-12-28 16:02:09,785 172.18.0.1 - - [28/Dec/2022 16:02:09] "[33mGET /messages/ HTTP/1.1[0m" 404 -
2022-12-28 16:02:12,568 172.18.0.1 - - [28/Dec/2022 16:02:12] "GET /messages HTTP/1.1" 200 -
2022-12-28 16:02:14,540 172.18.0.1 - - [28/Dec/2022 16:02:14] "GET /messages HTTP/1.1" 200 -
2022-12-28 16:06:46,326 table raw_rent_messages created
2022-12-28 16:06:46,328 current rows in table: 6542
2022-12-28 16:06:46,673 App initialized
2022-12-28 16:06:46,678 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 16:06:46,678 [33mPress CTRL+C to quit[0m
2022-12-28 16:06:50,173 172.18.0.1 - - [28/Dec/2022 16:06:50] "[32mGET /feed HTTP/1.1[0m" 308 -
2022-12-28 16:06:50,243 172.18.0.1 - - [28/Dec/2022 16:06:50] "GET /feed/ HTTP/1.1" 200 -
2022-12-28 16:09:46,879 table raw_rent_messages created
2022-12-28 16:09:46,881 current rows in table: 6542
2022-12-28 16:09:47,221 App initialized
2022-12-28 16:09:47,225 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 16:09:47,225 [33mPress CTRL+C to quit[0m
2022-12-28 16:09:53,384 172.18.0.1 - - [28/Dec/2022 16:09:53] "GET /feed/ HTTP/1.1" 200 -
2022-12-28 16:13:52,498 table raw_rent_messages created
2022-12-28 16:13:52,500 current rows in table: 6542
2022-12-28 16:13:52,841 App initialized
2022-12-28 16:13:52,845 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 16:13:52,845 [33mPress CTRL+C to quit[0m
2022-12-28 16:13:58,565 172.18.0.1 - - [28/Dec/2022 16:13:58] "GET /feed/ HTTP/1.1" 200 -
2022-12-28 16:14:15,926 172.18.0.1 - - [28/Dec/2022 16:14:15] "GET /feed/ HTTP/1.1" 200 -
2022-12-28 16:16:01,133 table raw_rent_messages created
2022-12-28 16:16:01,136 current rows in table: 6542
2022-12-28 16:16:01,484 App initialized
2022-12-28 16:16:01,488 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 16:16:01,488 [33mPress CTRL+C to quit[0m
2022-12-28 16:16:08,829 Exception on /feed/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/srv/src/service.py", line 59, in feed
    [sorted_msgs for _, sorted_msgs in sorted(zip(predicted_score, all_msgs))]
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
2022-12-28 16:16:08,830 172.18.0.1 - - [28/Dec/2022 16:16:08] "[35m[1mGET /feed/ HTTP/1.1[0m" 500 -
2022-12-28 16:18:00,260 table raw_rent_messages created
2022-12-28 16:18:00,262 current rows in table: 6542
2022-12-28 16:18:00,605 App initialized
2022-12-28 16:18:00,610 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 16:18:00,610 [33mPress CTRL+C to quit[0m
2022-12-28 16:18:06,488 Exception on /feed/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/srv/src/service.py", line 59, in feed
    [sorted_msgs for _, sorted_msgs in sorted(zip(predicted_score, all_msgs))]
TypeError: '<' not supported between instances of 'dict' and 'dict'
2022-12-28 16:18:06,489 172.18.0.1 - - [28/Dec/2022 16:18:06] "[35m[1mGET /feed/ HTTP/1.1[0m" 500 -
2022-12-28 16:18:34,139 table raw_rent_messages created
2022-12-28 16:18:34,142 current rows in table: 6542
2022-12-28 16:18:34,480 App initialized
2022-12-28 16:18:34,484 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 16:18:34,484 [33mPress CTRL+C to quit[0m
2022-12-28 16:18:42,519 Exception on /feed/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/srv/src/service.py", line 60, in feed
    [sorted_msgs for _, sorted_msgs in sorted(zip(predicted_score, all_msgs))]
TypeError: '<' not supported between instances of 'dict' and 'dict'
2022-12-28 16:18:42,520 172.18.0.1 - - [28/Dec/2022 16:18:42] "[35m[1mGET /feed/ HTTP/1.1[0m" 500 -
2022-12-28 16:20:11,201 table raw_rent_messages created
2022-12-28 16:20:11,203 current rows in table: 6542
2022-12-28 16:20:11,541 App initialized
2022-12-28 16:20:11,546 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 16:20:11,546 [33mPress CTRL+C to quit[0m
2022-12-28 16:20:21,235 Exception on /feed/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/srv/src/service.py", line 60, in feed
    [sorted_msgs for (_, sorted_msgs) in sorted(zip(predicted_score, all_msgs))]
TypeError: '<' not supported between instances of 'dict' and 'dict'
2022-12-28 16:20:21,237 172.18.0.1 - - [28/Dec/2022 16:20:21] "[35m[1mGET /feed/ HTTP/1.1[0m" 500 -
2022-12-28 16:21:18,220 table raw_rent_messages created
2022-12-28 16:21:18,222 current rows in table: 6542
2022-12-28 16:21:18,572 App initialized
2022-12-28 16:21:18,576 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 16:21:18,576 [33mPress CTRL+C to quit[0m
2022-12-28 16:21:26,534 Exception on /feed/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/srv/src/service.py", line 60, in feed
    print(sorted(zip(predicted_score, all_msgs)))
TypeError: '<' not supported between instances of 'dict' and 'dict'
2022-12-28 16:21:26,535 172.18.0.1 - - [28/Dec/2022 16:21:26] "[35m[1mGET /feed/ HTTP/1.1[0m" 500 -
2022-12-28 16:25:31,975 table raw_rent_messages created
2022-12-28 16:25:31,977 current rows in table: 6542
2022-12-28 16:25:32,316 App initialized
2022-12-28 16:25:32,320 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 16:25:32,320 [33mPress CTRL+C to quit[0m
2022-12-28 16:25:41,398 Exception on /feed/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/srv/src/service.py", line 60, in feed
    predicted_score = numpy.array(predicted_score)
NameError: name 'numpy' is not defined
2022-12-28 16:25:41,399 172.18.0.1 - - [28/Dec/2022 16:25:41] "[35m[1mGET /feed/ HTTP/1.1[0m" 500 -
2022-12-28 16:25:58,286 table raw_rent_messages created
2022-12-28 16:25:58,288 current rows in table: 6542
2022-12-28 16:25:58,632 App initialized
2022-12-28 16:25:58,636 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 16:25:58,636 [33mPress CTRL+C to quit[0m
2022-12-28 16:26:04,473 Exception on /feed/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/srv/src/service.py", line 63, in feed
    sorted_msgs = all_msgs[inds]
TypeError: only integer scalar arrays can be converted to a scalar index
2022-12-28 16:26:04,474 172.18.0.1 - - [28/Dec/2022 16:26:04] "[35m[1mGET /feed/ HTTP/1.1[0m" 500 -
2022-12-28 16:26:42,651 table raw_rent_messages created
2022-12-28 16:26:42,653 current rows in table: 6542
2022-12-28 16:26:43,017 App initialized
2022-12-28 16:26:43,021 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 16:26:43,021 [33mPress CTRL+C to quit[0m
2022-12-28 16:26:50,164 Exception on /feed/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/srv/src/service.py", line 64, in feed
    sorted_msgs = all_msgs[inds]
TypeError: only integer scalar arrays can be converted to a scalar index
2022-12-28 16:26:50,167 172.18.0.1 - - [28/Dec/2022 16:26:50] "[35m[1mGET /feed/ HTTP/1.1[0m" 500 -
2022-12-28 16:26:57,200 Exception on /feed/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/srv/src/service.py", line 64, in feed
    sorted_msgs = all_msgs[inds]
TypeError: only integer scalar arrays can be converted to a scalar index
2022-12-28 16:26:57,201 172.18.0.1 - - [28/Dec/2022 16:26:57] "[35m[1mGET /feed/ HTTP/1.1[0m" 500 -
2022-12-28 16:28:08,350 table raw_rent_messages created
2022-12-28 16:28:08,353 current rows in table: 6542
2022-12-28 16:28:08,692 App initialized
2022-12-28 16:28:08,696 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 16:28:08,696 [33mPress CTRL+C to quit[0m
2022-12-28 16:28:16,076 172.18.0.1 - - [28/Dec/2022 16:28:16] "GET /feed/ HTTP/1.1" 200 -
2022-12-28 16:29:41,545 table raw_rent_messages created
2022-12-28 16:29:41,547 current rows in table: 6542
2022-12-28 16:29:41,907 App initialized
2022-12-28 16:29:41,911 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 16:29:41,911 [33mPress CTRL+C to quit[0m
2022-12-28 16:29:48,477 172.18.0.1 - - [28/Dec/2022 16:29:48] "GET /feed/ HTTP/1.1" 200 -
2022-12-28 16:35:58,111 table raw_rent_messages created
2022-12-28 16:35:58,113 current rows in table: 6542
2022-12-28 16:35:58,119 App initialized
2022-12-28 16:35:58,123 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 16:35:58,123 [33mPress CTRL+C to quit[0m
2022-12-28 16:36:06,560 Exception on /feed/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/srv/src/service.py", line 56, in feed
    vectorized=vectorizer.transform([msg['msg_txt'] for msg in all_msgs])
NameError: name 'vectorizer' is not defined
2022-12-28 16:36:06,561 172.18.0.1 - - [28/Dec/2022 16:36:06] "[35m[1mGET /feed/ HTTP/1.1[0m" 500 -
2022-12-28 16:36:06,649 172.18.0.1 - - [28/Dec/2022 16:36:06] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2022-12-28 16:41:55,429 table raw_rent_messages created
2022-12-28 16:41:55,431 current rows in table: 6542
2022-12-28 16:41:55,773 App initialized
2022-12-28 16:41:55,777 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 16:41:55,777 [33mPress CTRL+C to quit[0m
2022-12-28 16:42:04,860 172.18.0.1 - - [28/Dec/2022 16:42:04] "GET /feed/ HTTP/1.1" 200 -
2022-12-28 16:42:18,480 172.18.0.1 - - [28/Dec/2022 16:42:18] "GET /feed/ HTTP/1.1" 200 -
2022-12-28 16:43:39,423 table raw_rent_messages created
2022-12-28 16:43:39,426 current rows in table: 6542
2022-12-28 16:43:39,778 App initialized
2022-12-28 16:43:39,782 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 16:43:39,782 [33mPress CTRL+C to quit[0m
2022-12-28 16:43:47,505 172.18.0.1 - - [28/Dec/2022 16:43:47] "GET /feed/ HTTP/1.1" 200 -
2022-12-28 16:44:07,992 172.18.0.1 - - [28/Dec/2022 16:44:07] "GET /feed/?limit=100 HTTP/1.1" 200 -
2022-12-28 16:44:18,257 172.18.0.1 - - [28/Dec/2022 16:44:18] "GET /feed/?limit=10000 HTTP/1.1" 200 -
2022-12-28 16:44:27,829 172.18.0.1 - - [28/Dec/2022 16:44:27] "GET /feed/?limit=1000000 HTTP/1.1" 200 -
2022-12-28 17:06:57,833 num rows for train: 5233
2022-12-28 17:06:58,194 best_score 0.86106
2022-12-28 17:07:30,211 num rows for train: 5233
2022-12-28 17:07:30,570 best_score 0.86106
2022-12-28 17:08:52,621 num rows for train: 5233
2022-12-28 17:08:54,418 best_score 0.83270
2022-12-28 17:09:11,655 num rows for train: 5233
2022-12-28 17:09:26,723 best_score 0.85393
2022-12-28 17:34:09,604 num rows for train: 5233
2022-12-28 17:34:27,153 best_score 0.86090
2022-12-28 17:34:44,410 num rows for train: 5233
2022-12-28 17:34:46,443 best_score 0.86260
2022-12-28 18:21:22,943 num rows for train: 5233
2022-12-28 18:22:13,040 num rows for train: 5233
2022-12-28 18:22:13,411 best_score 0.85658
2022-12-28 18:22:29,683 num rows for train: 5233
2022-12-28 18:22:30,051 best_score 0.85658
2022-12-28 18:22:30,754 Mine best_score 0.88538
2022-12-28 18:23:50,404 num rows for train: 5233
2022-12-28 18:23:50,767 best_score 0.86106
2022-12-28 18:23:51,470 Mine best_score 0.88538
2022-12-28 18:24:20,723 table raw_rent_messages created
2022-12-28 18:24:20,725 current rows in table: 6542
2022-12-28 18:24:21,086 App initialized
2022-12-28 18:24:21,090 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.4:5000
2022-12-28 18:24:21,090 [33mPress CTRL+C to quit[0m
2022-12-28 18:24:30,901 172.18.0.1 - - [28/Dec/2022 18:24:30] "GET /feed/?limit=1000000 HTTP/1.1" 200 -
2022-12-28 18:25:00,520 172.18.0.1 - - [28/Dec/2022 18:25:00] "GET /feed/ HTTP/1.1" 200 -
2023-01-08 09:23:59,209 num rows for train: 5233
2023-01-08 09:23:59,587 best_score 0.86106
2023-01-08 09:24:50,047 num rows for train: 5233
2023-01-08 09:24:50,410 best_score 0.86106
2023-01-08 09:25:02,443 Mine best_score 0.89575
2023-01-08 09:26:58,084 num rows for train: 5233
2023-01-08 09:26:58,447 best_score 0.86106
2023-01-08 09:27:18,038 Mine best_score 0.89575
2023-01-08 09:27:37,528 num rows for train: 5233
2023-01-08 09:27:37,890 best_score 0.86106
2023-01-08 09:27:47,659 Mine best_score 0.89453
2023-01-08 09:28:33,117 num rows for train: 5233
2023-01-08 09:28:33,480 best_score 0.86106
2023-01-08 09:29:00,650 Mine best_score 0.89575
2023-01-08 09:29:29,043 num rows for train: 5233
2023-01-08 09:29:29,405 best_score 0.86106
2023-01-08 09:29:43,227 Mine best_score 0.89147
2023-01-08 09:37:21,648 num rows for train: 5233
2023-01-08 09:37:22,011 best_score 0.86106
2023-01-08 09:37:34,132 Mine best_score 0.89147
2023-01-08 09:37:52,281 num rows for train: 5233
2023-01-08 09:37:52,644 best_score 0.86106
2023-01-08 09:38:05,200 Mine best_score 0.89575
2023-01-08 09:38:14,064 num rows for train: 5233
2023-01-08 09:38:14,426 best_score 0.86106
2023-01-08 09:38:27,412 Mine best_score 0.89320
2023-01-08 09:39:00,259 num rows for train: 5233
2023-01-08 09:39:00,623 best_score 0.86106
2023-01-08 09:39:31,724 num rows for train: 5233
2023-01-08 09:39:32,088 best_score 0.86106
2023-01-08 09:39:47,814 Mine best_score 0.88499
2023-01-08 09:51:17,093 num rows for train: 5233
2023-01-08 09:51:17,455 best_score 0.86106
2023-01-08 09:51:48,257 Mine best_score 0.86680
2023-01-08 09:53:30,806 num rows for train: 5233
2023-01-08 09:53:31,169 best_score 0.86106
2023-01-08 09:53:57,076 Mine best_score 0.88583
2023-01-08 09:54:22,527 num rows for train: 5233
2023-01-08 09:54:22,891 best_score 0.86106
2023-01-08 09:54:40,398 Mine best_score 0.89320
2023-01-08 09:55:01,356 num rows for train: 5233
2023-01-08 09:55:01,720 best_score 0.86106
2023-01-08 09:55:18,567 Mine best_score 0.87968
2023-01-08 09:55:32,770 num rows for train: 5233
2023-01-08 09:55:33,134 best_score 0.86106
2023-01-08 09:58:33,166 num rows for train: 5233
2023-01-08 09:58:33,530 best_score 0.86106
2023-01-08 09:59:02,232 Mine best_score 0.87179
2023-01-08 09:59:13,876 num rows for train: 5233
2023-01-08 09:59:14,239 best_score 0.86106
2023-01-08 09:59:26,549 Mine best_score 0.86051
2023-01-08 09:59:38,965 num rows for train: 5233
2023-01-08 09:59:39,328 best_score 0.86106
2023-01-08 10:00:10,331 Mine best_score 0.86680
2023-01-08 10:00:20,620 num rows for train: 5233
2023-01-08 10:00:21,028 best_score 0.86106
2023-01-08 10:00:35,239 Mine best_score 0.89062
2023-01-08 10:00:51,791 num rows for train: 5233
2023-01-08 10:00:52,156 best_score 0.86106
2023-01-08 10:01:07,176 Mine best_score 0.89669
2023-01-08 10:01:32,651 num rows for train: 5233
2023-01-08 10:01:33,016 best_score 0.86106
2023-01-08 10:01:47,635 Mine best_score 0.89147
2023-01-08 10:02:09,358 num rows for train: 5233
2023-01-08 10:02:09,725 best_score 0.86106
2023-01-08 10:02:22,363 Mine best_score 0.89749
2023-01-08 10:04:17,350 num rows for train: 5233
2023-01-08 10:04:17,713 best_score 0.86106
2023-01-08 10:04:30,019 Mine best_score 0.89749
2023-01-08 11:29:44,223 num rows for train: 5233
2023-01-08 11:29:44,585 best_score 0.86106
2023-01-08 11:29:56,876 Mine best_score 0.89749
2023-01-08 11:31:53,381 num rows for train: 5233
2023-01-08 11:31:53,744 best_score 0.86106
2023-01-08 11:32:06,078 Mine best_score 0.89749
2023-01-08 11:33:29,028 num rows for train: 5233
2023-01-08 11:33:29,424 best_score 0.86106
2023-01-08 11:33:41,910 Mine best_score 0.89961
2023-01-08 14:05:50,354 num rows for train: 5233
2023-01-08 14:05:50,718 best_score 0.86106
2023-01-08 14:06:03,183 Mine best_score 0.89961
2023-01-08 14:06:51,877 num rows for train: 5233
2023-01-08 14:06:52,324 best_score 0.86106
2023-01-08 14:07:04,870 Mine best_score 0.89961
2023-01-08 14:07:50,984 num rows for train: 5233
2023-01-08 14:07:51,346 best_score 0.86106
2023-01-08 14:08:03,782 Mine best_score 0.89961
2023-01-08 14:42:30,720 num rows for train: 5233
2023-01-08 14:42:31,083 best_score 0.86106
2023-01-08 14:42:43,755 Mine best_score 0.85824
2023-01-08 14:43:15,890 num rows for train: 5233
2023-01-08 14:43:16,253 best_score 0.86106
2023-01-08 14:43:28,670 Mine best_score 0.85714
2023-01-08 14:44:10,771 num rows for train: 5233
2023-01-08 14:44:11,131 best_score 0.86106
2023-01-08 14:44:23,884 Mine best_score 0.85496
2023-01-08 14:45:45,331 num rows for train: 5233
2023-01-08 14:45:45,693 best_score 0.86106
2023-01-08 14:45:58,111 Mine best_score 0.89961
2023-01-08 14:46:20,461 num rows for train: 5233
2023-01-08 14:46:20,824 best_score 0.86106
2023-01-08 14:46:34,186 Mine best_score 0.89575
2023-01-08 14:48:09,553 num rows for train: 5233
2023-01-08 14:48:09,916 best_score 0.86106
2023-01-08 14:48:33,499 Mine best_score 0.89961
2023-01-08 14:49:16,585 num rows for train: 5233
2023-01-08 14:49:16,948 best_score 0.86106
2023-01-08 14:49:29,393 Mine best_score 0.89961
2023-01-08 14:50:56,673 num rows for train: 5233
2023-01-08 14:50:57,036 best_score 0.86106
2023-01-08 14:51:09,528 Mine best_score 0.89961
2023-01-08 14:51:40,722 num rows for train: 5233
2023-01-08 14:51:41,087 best_score 0.86106
2023-01-08 14:51:53,534 Mine best_score 0.67990
2023-01-08 14:52:33,497 num rows for train: 5233
2023-01-08 14:52:33,861 best_score 0.86106
2023-01-08 14:52:46,232 Mine best_score 0.67990
2023-01-08 14:52:57,914 num rows for train: 5233
2023-01-08 14:52:58,283 best_score 0.86106
2023-01-08 14:53:10,715 Mine best_score 0.87221
2023-01-08 14:53:20,002 num rows for train: 5233
2023-01-08 14:53:20,366 best_score 0.86106
2023-01-08 14:53:32,781 Mine best_score 0.87221
2023-01-08 14:55:06,550 num rows for train: 5233
2023-01-08 14:55:06,912 best_score 0.86106
2023-01-08 14:55:19,350 Mine best_score 0.89961
2023-01-08 14:56:03,955 num rows for train: 5233
2023-01-08 14:56:04,315 best_score 0.86106
2023-01-08 14:56:16,775 Mine best_score 0.89888
2023-01-08 14:57:00,778 num rows for train: 5233
2023-01-08 14:57:01,143 best_score 0.86106
2023-01-08 15:00:27,516 num rows for train: 5233
2023-01-08 15:00:27,880 best_score 0.86106
2023-01-08 15:00:41,260 Mine best_score 0.90056
2023-01-08 15:01:06,678 table raw_rent_messages created
2023-01-08 15:01:06,680 current rows in table: 6542
2023-01-08 15:01:07,040 App initialized
2023-01-08 15:01:07,043 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.3:5000
2023-01-08 15:01:07,043 [33mPress CTRL+C to quit[0m
2023-01-08 15:01:15,215 172.18.0.1 - - [08/Jan/2023 15:01:15] "[33mGET / HTTP/1.1[0m" 404 -
2023-01-08 15:01:15,262 172.18.0.1 - - [08/Jan/2023 15:01:15] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2023-01-08 15:01:40,962 172.18.0.1 - - [08/Jan/2023 15:01:40] "GET /messages HTTP/1.1" 200 -
2023-01-08 15:01:51,085 172.18.0.1 - - [08/Jan/2023 15:01:51] "[33mGET /id HTTP/1.1[0m" 404 -
2023-01-08 15:02:21,728 172.18.0.1 - - [08/Jan/2023 15:02:21] "GET /messages/0 HTTP/1.1" 200 -
2023-01-08 15:02:27,148 172.18.0.1 - - [08/Jan/2023 15:02:27] "[32mGET /feed HTTP/1.1[0m" 308 -
2023-01-08 15:02:35,822 172.18.0.1 - - [08/Jan/2023 15:02:35] "GET /feed/ HTTP/1.1" 200 -
2023-01-08 17:37:04,815 num rows for train: 5233
2023-01-08 17:37:05,188 best_score 0.86106
2023-01-08 17:37:18,587 Mine best_score 0.90056
